FROM {{GO_BUILD_BASE}}

RUN useradd -ms /bin/bash stratos && \
    mkdir -p /home/stratos && \
    chown -R stratos /home/stratos && \
    chgrp -R users /home/stratos

RUN cd / && wget https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-{{NODE_ARCH}}.tar.gz && \
    tar -xf node-v20.11.1-linux-{{NODE_ARCH}}.tar.gz && \
    rm node-v20.11.1-linux-{{NODE_ARCH}}.tar.gz

ENV USER=stratos

ENV PATH=$PATH:/node-v20.11.1-linux-{{NODE_ARCH}}/bin

USER stratos

WORKDIR /home/stratos
