name: container-push-base-images-develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: 'Log into GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{secrets.GH_PACKAGES_USER}}
          password: ${{secrets.GH_PACKAGES_TOKEN}}
      - name: 'Checkout current develop'
        uses: actions/checkout@v4
        with:
          ref: "develop"
      - name: 'Build stratos base images'
        run: |
          ./deploy/stratos-base-images/build-base-images.sh -r ghcr.io -o ${{secrets.GH_PACKAGES_USER}} -p -s
      - name: 'Build stratos image'
        run: |
          docker build -f deploy/Dockerfile.all-in-one . -t ghcr.io/${{secrets.GH_PACKAGES_USER}}/stratos:rockylinux9
      - name: 'Push stratos image'
        run: |
          docker push ghcr.io/${{secrets.GH_PACKAGES_USER}}/stratos:rockylinux9
