name: container-push-base-images-develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: 'Log into GHCR'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{secrets.GH_PACKAGES_USER}}
          password: ${{secrets.GH_PACKAGES_TOKEN}}
      - name: 'Checkout current develop'
        uses: actions/checkout@v3
        with:
          ref: "develop"
      - name: 'Build stratos base images'
        run: |
          ./deploy/stratos-base-images/build-base-images.sh -r ghcr.io -o ${{secrets.GH_PACKAGES_USER}} -p -s
